for /l %%x in (0,1,8) do (copy usauc*___________0%%x.* "G:\Data\TANA\2012\tana_Folder_Structure\combined\00 - 08 Streets\")
for /l %%x in (0,1,9) do (copy usauc*___________a%%x.* "G:\Data\TANA\2012\tana_Folder_Structure\combined\a0 - a9 Administrative Areas\")
for /l %%x in (1,1,9) do (copy usauc*___________oa0%%x.* "G:\Data\TANA\2012\tana_Folder_Structure\combined\oa- Other Areas Census Geography")
for /l %%x in (10,1,11) do (copy usauc*___________oa%%x.* "G:\Data\TANA\2012\tana_Folder_Structure\combined\oa- Other Areas Census Geography")
REM not sure what goes in here : for /l %%x in (0,1,9) do (copy usauc*___________*%%x.* "G:\Data\TANA\2012\tana_Folder_Structure\combined\roads- 00-08 Streets combined\")


for %%y in (usauc*___________00.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\00")
for %%y in (usauc*___________01.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\01")
for %%y in (usauc*___________02.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\02")
for %%y in (usauc*___________03.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\03")
for %%y in (usauc*___________04.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\04")
for %%y in (usauc*___________05.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\05")
for %%y in (usauc*___________06.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\06")
for %%y in (usauc*___________07.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\07")
for %%y in (usauc*___________08.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\08")

for %%y in (usauc*___________a0.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\a0")
for %%y in (usauc*___________a1.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\a1")
for %%y in (usauc*___________a2.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\a2")
for %%y in (usauc*___________a3.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\a3")
for %%y in (usauc*___________a4.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\a4")
for %%y in (usauc*___________a5.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\a5")
for %%y in (usauc*___________a6.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\a6")
for %%y in (usauc*___________a7.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\a7")
for %%y in (usauc*___________a8.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\a8")
for %%y in (usauc*___________a9.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\a9")

for %%y in (usauc*___________2r.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\2r- Level 2 Roads")
for %%y in (usauc*___________aa.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\aa- Administrative Areas")
for %%y in (usauc*___________aaea.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\aaea- Address Area Extended Attributes")
for %%y in (usauc*___________aanm.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\aanm- Address Area Names")
for %%y in (usauc*___________ab.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\ab- Address Area Boundary Element Belonging to Address Area")
for %%y in (usauc*___________ad.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\ad- Administrative Area Structure Definitions")
for %%y in (usauc*___________ae.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\ae- Administrative Area Extended Attributes")
for %%y in (usauc*___________ai.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\ai- Area Replaced by Index Area")
for %%y in (usauc*___________an.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\an- Administrative Area Names")
for %%y in (usauc*___________ap.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\ap- Administrative Places")
for %%y in (usauc*___________as.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\as- Structure Areas")
for %%y in (usauc*___________axas.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\axas- Administrative Areas")
for %%y in (usauc*___________axav.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\axav- Administrative Areas")
for %%y in (usauc*___________ba.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\ba- Built-Up Area in Named Area")
for %%y in (usauc*___________be.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\be- Built Up Area Extended Attributes")
for %%y in (usauc*___________bl.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\bl- Boundary Lines")
for %%y in (usauc*___________bn.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\bn- Built Up Area Names")
for %%y in (usauc*___________bu.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\bu- Built Up Areas")
for %%y in (usauc*___________cf.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\cf- Center Point of Freeway")
for %%y in (usauc*___________cn.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\cn- Conversion Records")
for %%y in (usauc*___________ep.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\ep- Administrative Place Extended Attributes")
for %%y in (usauc*___________fe.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\fe- Ferries")
for %%y in (usauc*___________gc.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\gc- Geocode")
for %%y in (usauc*___________ig.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\ig- Intersection Index")
for %%y in (usauc*___________ih.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\ih- Intermediate House Numbers")
for %%y in (usauc*___________is.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\is- Intersections")
for %%y in (usauc*___________jc.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\jc- Junctions")
for %%y in (usauc*___________jcea.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\jcea- Junctions Extended Attributes")
for %%y in (usauc*___________lc.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\lc- Land Cover Areas")
for %%y in (usauc*___________ld.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\ld- Lane Direction Information")
for %%y in (usauc*___________le.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\le- Lane End")
for %%y in (usauc*___________lf.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\lf- Direction of Traffic Flow for Lane")
for %%y in (usauc*___________li.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\li- Lane Type Info")
for %%y in (usauc*___________ll.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\ll- Lane Divider Information")
for %%y in (usauc*___________ln.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\ln- Lane Connectivitiy Information")
for %%y in (usauc*___________locff.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\locff- Locality Index Find Feature")
for %%y in (usauc*___________locfp.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\locfp- Locality Index Feature Priority")
for %%y in (usauc*___________llocnm.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\llocnm- Locality Index Names")
for %%y in (usauc*___________lp.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\lp Lane Connectivity Path")
for %%y in (usauc*___________ls.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\ls- Structure Lines")
for %%y in (usauc*___________lt.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\lt- Time Domains for Direction of Traffic Flow")
for %%y in (usauc*___________lu.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\lu- Land Use Areas")
for %%y in (usauc*___________lxea.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\lxea- Land Use and Land Cover Extended Attributes")
for %%y in (usauc*___________lxnm.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\lxnm- Land Use and Land Cover Names")
for %%y in (usauc*___________mn.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\mn- Maneuvers")
for %%y in (usauc*___________mp.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\mp- Maneuver Path Index")
for %%y in (usauc*___________np.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\np- Administrative Place Names")
for %%y in (usauc*___________nw.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\nw- Network")
for %%y in (usauc*___________nwea.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\nwea- Network Extended Attributes")

for %%y in (usauc*___________oa01.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\oa01")
for %%y in (usauc*___________oa02.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\oa02")
for %%y in (usauc*___________oa03.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\oa03")
for %%y in (usauc*___________oa04.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\oa04")
for %%y in (usauc*___________oa05.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\oa05")
for %%y in (usauc*___________oa06.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\oa06")
for %%y in (usauc*___________oa07.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\oa07")
for %%y in (usauc*___________oa08.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\oa08")
for %%y in (usauc*___________oa09.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\oa08")
for %%y in (usauc*___________oa10.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\oa10")
for %%y in (usauc*___________oa11.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\oa11")


for %%y in (usauc*___________oaea.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\oaea- Other Areas Extended Attributes")
for %%y in (usauc*___________oanm.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\oanm- Other Areas Names")
for %%y in (usauc*___________ol.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\ol- Official Languages")
for %%y in (usauc*___________pc.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\pc- Postal Code Information on Transportation Element")
for %%y in (usauc*___________pcnm.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\pcnm- Postal Code Name Information")
for %%y in (usauc*___________pd.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\pd- Postal Districts")
for %%y in (usauc*___________pdea.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\pdea- Postal Districts Extended Attributes")
for %%y in (usauc*___________pdnm.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\pdnm- Postal Districts Names")
for %%y in (usauc*___________pe.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\pe- Point of Interest at Junction Relation")
for %%y in (usauc*___________pi.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\pi- Points of Interest and Related attr")
for %%y in (usauc*___________piea.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\piea- Points of Interest Extended Attributes")
for %%y in (usauc*___________pinm.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\pinm- Points of Interest Names")
for %%y in (usauc*___________pm.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\pm-")
for %%y in (usauc*___________pp.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\pp- Place Within Place Relation")
for %%y in (usauc*___________pr.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\pr- Service POI Belonging to Service POI")
for %%y in (usauc*___________ps.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\ps- Structure Points")
for %%y in (usauc*___________rd.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\rd- TMC Information Along Road Element")
for %%y in (usauc*___________rn.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\rn- Route Numbers")
for %%y in (usauc*___________rr.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\rr- Railways")
for %%y in (usauc*___________rrea.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\rrea- Rail Roads Extended Attributes")
for %%y in (usauc*___________rrnm.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\rrnm- Rail Roads Names")
for %%y in (usauc*___________rs.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\rs- Restrictions")
for %%y in (usauc*___________sa.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\sa- Service in Named Area")
for %%y in (usauc*___________sc.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\sc- Official Street Codes")
for %%y in (usauc*___________se.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\se- Structure Transportation Elements Relation")
for %%y in (usauc*___________sg.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\sg- Signpost")
for %%y in (usauc*___________si.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\si- Signpost Information")
for %%y in (usauc*___________sl.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\sl- Speed Restricition per Lane")
for %%y in (usauc*___________sm.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\sm- Centers of Settlements")
for %%y in (usauc*___________smea.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\smea- Centers of Settlements Extended Attributes")
for %%y in (usauc*___________smnm.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\smnm- Centers of Settlements Names")
for %%y in (usauc*___________sp.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\sp- Signpost Path Index")
for %%y in (usauc*___________sr.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\sr- Speed Restrictions")
for %%y in (usauc*___________st.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\st- Speed Restriction Time Domains")
for %%y in (usauc*___________sxea.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\sxea- Structure Extended Attributes")
for %%y in (usauc*___________sxnm.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\sxnm- Structure Names")
for %%y in (usauc*___________ta.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\ta- Transportation Element Belonging to Area")
for %%y in (usauc*___________tc.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\tc- TMC Location Index")
for %%y in (usauc*___________td.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\td- Time Domains")
for %%y in (usauc*___________tg.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\tg- TMC Path Index")
for %%y in (usauc*___________ti.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\ti- TMC Path Location Index")
for %%y in (usauc*___________tl.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\tl- TMC Location")
for %%y in (usauc*___________to.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\to- Tourist Roads")
for %%y in (usauc*___________tp.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\tp- TMC Path")
for %%y in (usauc*___________ts.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\ts- Traffic Signs")
for %%y in (usauc*___________tt.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\tt- Traffic Sign Along Road Element")
for %%y in (usauc*___________vr.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\vr- Vicinity Relation")
for %%y in (usauc*___________wa.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\wa- Water Bodies")
for %%y in (usauc*___________wl.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\wl- Water Lines")
for %%y in (usauc*___________wxea.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\wxea- Water Areas Lines Extended Attributes")
for %%y in (usauc*___________wxnm.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\wxnm- Water Areas Lines Names")
for %%y in (usauc*___________xo.*) do (copy %%y "G:\Data\TANA\2012\tana_Folder_Structure\xo- XML Object Reference")