for /l %%x in (0,1,8) do mkdir "G:\Data\TANA\2012\tana_Folder_Structure\0"%%x
for /l %%x in (0,1,9) do mkdir "G:\Data\TANA\2012\tana_Folder_Structure\a"%%x
for /l %%x in (1,1,9) do mkdir "G:\Data\TANA\2012\tana_Folder_Structure\oa0"%%x
for /l %%x in (10,1,11) do mkdir "G:\Data\TANA\2012\tana_Folder_Structure\oa"%%x

mkdir "combined\00 - 08 Streets"
mkdir "2r- Level 2 Roads"
mkdir "combined\a0 - a9 Administrative Areas"
mkdir "aa- Administrative Areas"
mkdir "aaea- Address Area Extended Attributes"
mkdir "aanm- Address Area Names"
mkdir "ab- Address Area Boundary Element Belonging to Address Area"
mkdir "ad- Administrative Area Structure Definitions"
mkdir "ae- Administrative Area Extended Attributes"
mkdir "ai- Area Replaced by Index Area"
mkdir "an- Administrative Area Names"
mkdir "ap- Administrative Places"
mkdir "as- Structure Areas"
mkdir "axas- Administrative Areas"
mkdir "axav- Administrative Areas"
mkdir "ba- Built-Up Area in Named Area"
mkdir "be- Built Up Area Extended Attributes"
mkdir "bl- Boundary Lines"
mkdir "bn- Built Up Area Names"
mkdir "bu- Built Up Areas"
mkdir "cf- Center Point of Freeway"
mkdir "cn- Conversion Records"
mkdir "ep- Administrative Place Extended Attributes"
mkdir "fe- Ferries"
mkdir "gc- Geocode"
mkdir "ig- Intersection Index"
mkdir "ih- Intermediate House Numbers"
mkdir "is- Intersections"
mkdir "jc- Junctions"
mkdir "jcea- Junctions Extended Attributes"
mkdir "lc- Land Cover Areas"
mkdir "ld- Lane Direction Information"
mkdir "le- Lane End"
mkdir "lf- Direction of Traffic Flow for Lane"
mkdir "li- Lane Type Info"
mkdir "ll- Lane Divider Information"
mkdir "ln- Lane Connectivitiy Information"
mkdir "locff- Locality Index Find Feature"
mkdir "locfp- Locality Index Feature Priority"
mkdir "locnm- Locality Index Names"
mkdir "lp Lane Connectivity Path"
mkdir "ls- Structure Lines"
mkdir "lt- Time Domains for Direction of Traffic Flow"
mkdir "lu- Land Use Areas"
mkdir "lxea- Land Use and Land Cover Extended Attributes"
mkdir "lxnm- Land Use and Land Cover Names"
mkdir "mn- Maneuvers"
mkdir "mp- Maneuver Path Index"
mkdir "np- Administrative Place Names"
mkdir "nw- Network"
mkdir "nwea- Network Extended Attributes"
mkdir "combined\oa- Other Areas Census Geography"
mkdir "oaea- Other Areas Extended Attributes"
mkdir "oanm- Other Areas Names"
mkdir "ol- Official Languages"
mkdir "pc- Postal Code Information on Transportation Element"
mkdir "pcnm- Postal Code Name Information"
mkdir "pd- Postal Districts"
mkdir "pdea- Postal Districts Extended Attributes"
mkdir "pdnm- Postal Districts Names"
mkdir "pe- Point of Interest at Junction Relation"
mkdir "pi- Points of Interest and Related attr"
mkdir "piea- Points of Interest Extended Attributes"
mkdir "pinm- Points of Interest Names"
mkdir "pm-"
mkdir "pp- Place Within Place Relation"
mkdir "pr- Service POI Belonging to Service POI"
mkdir "ps- Structure Points"
mkdir "rd- TMC Information Along Road Element"
mkdir "rn- Route Numbers"
mkdir "roads- 00-08 Streets combined"
mkdir "rr- Railways"
mkdir "rrea- Rail Roads Extended Attributes"
mkdir "rrnm- Rail Roads Names"
mkdir "rs- Restrictions"
mkdir "sa- Service in Named Area"
mkdir "sc- Official Street Codes"
mkdir "se- Structure Transportation Elements Relation"
mkdir "sg- Signpost"
mkdir "si- Signpost Information"
mkdir "sl- Speed Restricition per Lane"
mkdir "sm- Centers of Settlements"
mkdir "smea- Centers of Settlements Extended Attributes"
mkdir "smnm- Centers of Settlements Names"
mkdir "sp- Signpost Path Index"
mkdir "sr- Speed Restrictions"
mkdir "st- Speed Restriction Time Domains"
mkdir "sxea- Structure Extended Attributes"
mkdir "sxnm- Structure Names"
mkdir "ta- Transportation Element Belonging to Area"
mkdir "tc- TMC Location Index"
mkdir "td- Time Domains"
mkdir "tg- TMC Path Index"
mkdir "ti- TMC Path Location Index"
mkdir "tl- TMC Location"
mkdir "to- Tourist Roads"
mkdir "tp- TMC Path"
mkdir "ts- Traffic Signs"
mkdir "tt- Traffic Sign Along Road Element"
mkdir "vr- Vicinity Relation"
mkdir "wa- Water Bodies"
mkdir "wl- Water Lines"
mkdir "wxea- Water Areas Lines Extended Attributes"
mkdir "wxnm- Water Areas Lines Names"
mkdir "xo- XML Object Reference"
