# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# RegionalClipForDownload.py
# Created on: 2013-04-03 10:57:56.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: RegionalClipForDownload <Clip_Features> <Input_Features> <File_GDB_Location> <File_GDB_Name> <Text_File> <ShpLocation> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Clip_Features = arcpy.GetParameterAsText(0)
arcpy.AddMessage(Clip_Features)

File_GDB_Location = arcpy.GetParameterAsText(1)
File_GDB_Location = File_GDB_Location.replace("\\", "\\\\")
File_GDB_Name = arcpy.GetParameterAsText(2)
arcpy.AddMessage(File_GDB_Name)

Output_GDBPath = File_GDB_Location + "\\\\" + File_GDB_Name
arcpy.AddMessage(Output_GDBPath)

Text_File = arcpy.GetParameterAsText(3)

ShpLocation = arcpy.GetParameterAsText(4)
ShpLocation = ShpLocation.replace("\\", "\\\\")

##if arcpy.Exists(Output_GDBPath):
##    arcpy.Delete_management(Output_GDBPath)
try:    
    # Process: Create File GDB
    arcpy.CreateFileGDB_management(File_GDB_Location, File_GDB_Name, "CURRENT")
    arcpy.AddMessage("Created GDB")
except:
    arcpy.AddError("Unable to create geodatabase.  Make sure it doesn't already exist.")

fcListFile = open(Text_File, 'r')
fcList = [line.split(',') for line in fcListFile]
arcpy.AddMessage(fcList)

for fc in fcList[0]:
    try:
        fc=fc.strip()
        fcPath = ShpLocation + "\\\\" + fc
## For shapefiles:
        ##fcPath = ShpLocation + "\\\\" + fc+ r".shp"
        fcExists = arcpy.Exists(fcPath)
        if fcExists:
            # Process: Clip
            arcpy.AddMessage(Output_GDBPath + r".gdb\\" + fc)
## For shapefiles:
##            arcpy.Clip_analysis(ShpLocation + "\\\\" + fc + r".shp", Clip_Features, Output_GDBPath + r".gdb\\" + fc, "")
            arcpy.Clip_analysis(ShpLocation + "\\\\" + fc, Clip_Features, Output_GDBPath + r".gdb\\" + fc, "")
            arcpy.AddMessage("Successfully clipped and copied " + str(fc))
        else:
            arcpy.AddWarning("Error: " + str(fcPath) + " does not exist. Clip failed.")
    except:
        arcpy.AddWarning("Could not clip " + str(fc))

    
